apiVersion: v1
kind: Service
metadata:
  name: sfc-scheme
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-scheme
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Internal ClusterIP service for Scheme component in SFC application"
spec:
  selector:
    app.kubernetes.io/name: sfc-scheme
  type: ClusterIP
  ports:
    - name: sfc-scheme-cluster-service-http-port
      protocol: TCP
      port: 7865
      targetPort: 7865
    - name: sfc-scheme-cluster-service-https-port
      protocol: TCP
      port: 7866
      targetPort: 7866
  internalTrafficPolicy: Cluster