<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SFC.Scheme.Contracts</PackageId>
    <Version>0.0.3</Version>
    <Authors>Andrii Kryvoruk</Authors>
    <Company>SFC</Company>
    <Product>SFC</Product>
    <PackageTags>Street Football Club;SFC;Scheme;Contracts</PackageTags>
    <Description>
      Contracts from Scheme service for SFC project
    </Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Grpc.Core.Api" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.69.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Enums\sorting_direction.proto" />
    <Protobuf Include="Headers\auditable_header.proto" />
    <Protobuf Include="Headers\pagination_header.proto" />
    <Protobuf Include="Messages\Scheme\Data\GetAll\get_all_scheme_data_request.proto" />
    <Protobuf Include="Messages\Scheme\Data\GetAll\get_all_scheme_data_response.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\Filters\get_game_team_schemes_filter.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\Filters\game_team_schemes_general_profile_filter.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\Filters\game_team_schemes_players_filter.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\Filters\game_team_schemes_players_stats_filter.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\Filters\game_team_schemes_profile_filter.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\get_game_team_schemes_request.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Find\get_game_team_schemes_response.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Get\get_game_team_scheme_request.proto" />
    <Protobuf Include="Messages\Scheme\Game\Team\Get\get_game_team_scheme_response.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\Filters\team_schemes_profile_filter.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\Filters\team_schemes_players_filter.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\Filters\team_schemes_players_stats_filter.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\Filters\team_schemes_general_profile_filter.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\Filters\get_team_schemes_filter.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\get_team_schemes_request.proto" />
    <Protobuf Include="Messages\Scheme\Team\Find\get_team_schemes_response.proto" />
    <Protobuf Include="Messages\Scheme\Team\Get\get_team_scheme_request.proto" />
    <Protobuf Include="Messages\Scheme\Team\Get\get_team_scheme_response.proto" />
    <Protobuf Include="Models\Common\int32_array.proto" />
    <Protobuf Include="Models\Common\pagination.proto" />
    <Protobuf Include="Models\Common\range_limit.proto" />
    <Protobuf Include="Models\Common\sorting.proto" />
    <Protobuf Include="Models\Scheme\Data\data_value.proto" />
    <Protobuf Include="Models\Scheme\Data\formation_data_value.proto" />
    <Protobuf Include="Models\Scheme\Data\formation_position_data_value.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme_formation.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme_formation_player.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme_formation_player_position.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme_general_profile.proto" />
    <Protobuf Include="Models\Scheme\Game\Team\game_team_scheme_profile.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme_formation.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme_formation_player_position.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme_formation_player.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme_general_profile.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme_profile.proto" />
    <Protobuf Include="Models\Scheme\Team\team_scheme.proto" />
    <Protobuf Include="Services\scheme_data_service.proto" />
    <Protobuf Include="Services\game_team_scheme_service.proto" />
    <Protobuf Include="Services\team_scheme_service.proto" />
  </ItemGroup>

</Project>
